CREATE DATABASE IF NOT EXISTS laraveldb;

CREATE USER 'laraveluser'@'%' IDENTIFIED BY '1234';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `laraveldb`.* TO 'laraveluser'@'%';

FLUSH PRIVILEGES;